### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by tulir** [vvenla/Tsoha-Bootstrap#1]
Koodi ladattu commitin 2193b0aee54549ab695d36327acc24f05da607fe (31.12. 20:16) kohdalla.

## Tietosisältö ja -kanta
Tietosisältö täyttää vaatimukset: monesta-moneen suhde, kaksi CRUD-nelikkoa, kolme tietokohdetta löytyvät.

[Taulujen luontikyselyissä](https://github.com/vvenla/Tsoha-Bootstrap/blob/master/sql/create_tables.sql#L7-L18) `Tehtava`-luokka pitäisi varmaan luoda `Luokka`-luokan jälkeen, sillä `Tehtava`:n `luokkaId` viittaa `Luokka`:n `id`-kenttään.

Lisäksi testidataa voisi hieman laajentaa lisäämällä esimerkiksi toisen käyttäjän ja jaettuja tehtäviä.

## HTML ja ulkoasu
Ulkoasu on selkeä ja HTML-tiedostot vaikuttavat pääosin hyviltä.

[paanakyma.html](https://github.com/vvenla/Tsoha-Bootstrap/blob/master/app/views/suunnitelmat/paanakyma.html#L20-L21):ssä rivien 20 ja 21 välistä taitaa puuttua sulkeva `td`-tagi.

Luettavuuden kannalta olisi hyvä laittaa avaava ja sulkeva tagi joko molemmat samalle riville tai molemmat omille riveilleen. [tehtavanLisays.html](https://github.com/vvenla/Tsoha-Bootstrap/blob/master/app/views/suunnitelmat/tehtavanLisays.html#L20-L21):n riveillä 20-21 oleva nappi on hieman hankala lukea.

**Comment by vvenla** [comment]
Kiitos katselmoinnista! Taulujen luonnin korjasinkin jo ennen kuin ehdin tätä lukemaan.

Testidataa lisätty, ja html-tiedostojen luettavuuteen koitan kiinnittää huomiota, oli hyödyllinen palaute.
