### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Melchan** [vvenla/Tsoha-Bootstrap#2]
Koodi on pääsääntöisesti helppo lukuista ja kansio rakenne näyttää selkeältä. 

En tiedä onko olennaista, mutta testi datan määrän lisäyksellä voi testata miltä kaikkien taskien listaaminen näyttää kun se täyttää koko sivun. 

Dokumentaatio erittäin nätti. Relaatiotietokantakaavio ja luokkakaavio näyttävät hieman sumeilta ruudullani, muuten vaikea sanoa mitään. 

Helloworld.html ja helloworld.php:lle ei näytä olevan mitään käyttöä. Ne voi varmaan siistiä nytten tai sitten lopuksi. 

Olisimpa itse näin pitkällä omassa työssäni tsemppiä!

**Comment by vvenla** [comment]
Kiitos katselmoinnista! Testidataa on tosiaan helppo lisätä, voisinkin kokeilla tuota koko sivun täyttämistä.
